version: "3.9"
services:

  python_test:
    container_name: task_helpers_python_test
    build: .
    volumes:
      - ./htmlcov:/code/htmlcov
    restart: "no"
    command:
      - /bin/sh
      - -c
      - |
        coverage run -m unittest
        coverage html
        coverage xml
    depends_on:
      - "redis_test"
    environment:
      - REDIS_HOST=redis_test
      - REDIS_PORT=6379
      - REDIS_DB=0

  redis_test:
    container_name: task_helpers_redis_test
    image: redis
    restart: "no"
    command: redis-server --loglevel warning
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - ALLOW_EMPTY_PASSWORD=yes
